version: '3'

services:
  proxy: 
    build: 
      context: nginx
    image: marcomoreira94/proxy
    container_name: proxy
    tty: true
    ports:
      - 8080:80
    networks:
      - nodenet
    entrypoint: dockerize -wait tcp://node-app:3000 -timeout 20s /docker-entrypoint.sh
    command: nginx -g "daemon off;"
    depends_on:
      - node-app

  node-app:
    build: 
      context: nodejs
    image: marcomoreira94/node-app
    container_name: node-app
    tty: true
    volumes:
      - ./nodejs:/usr/src/app
    networks:
      - nodenet
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    depends_on:
      - db
    
  db:
    image: mysql
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - nodenet
    
networks:
  nodenet:
    driver: bridge