version: '3'

services:
  app:
    build: 
      context: node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    # entrypoint: wait-for db:3306 -t 40 -- docker-entrypoint.sh
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    depends_on: #Espera o container db subir primeiro para depois subir o node (mas não espera que o container esteja pronto)
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER = root
    networks:
      - node-network

networks:

  node-network:
    driver: bridge